import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Camila & Juan Pablo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          <nav>
            <ul style={{ display: "flex", gap: "1rem" }}>
              <Link href="/">Home</Link>
              <Link href="/story">Historia</Link>
              <Link href="/gallery">Galeria</Link>
              <Link href="/party">Sobre la fiesta</Link>
              <Link href="/faq">FAQ</Link>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
